name: Main

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra:
          - "11.0"
          - "10.4"
          - "10.3.3"
          - "10.3.2"
          - "10.3.1"
          - "10.3"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Install Gradle
        uses: gradle/gradle-build-action@v2.12.0
        
      - name: Install Ghidra ${{ matrix.ghidra }}
        uses: antoniovazquezblanco/setup-ghidra@v1.2.0
        with:
          auth_token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ matrix.ghidra }}

      - name: Build
        run: gradle -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GhidraMinesweeper_Ghidra_${{ matrix.ghidra }}
          path: dist/*.zip

  release:
    runs-on: "ubuntu-latest"
    needs: build
    if: contains(github.ref, 'refs/tags/v')

    steps:
    - name: Download binaries
      uses: actions/download-artifact@v4

    - name: Release stable
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        title: "Ghidra Minesweeper ${{github.ref_name}}"
        files: GhidraMinesweeper_Ghidra_*/*.zip
